# Generated by Django 5.2.7 on 2025-11-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Galleries'},
        ),
    ]
